# Generated by Django 4.1.3 on 2022-11-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree_tool', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_core',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_elective',
        ),
    ]
