# Generated by Django 4.1.3 on 2022-11-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree_tool', '0003_remove_course_is_core_remove_course_is_elective'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LevelingCourse',
        ),
    ]
