# Generated by Django 4.1.3 on 2022-12-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_tool', '0005_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
