# Generated by Django 4.1.3 on 2022-12-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_tool', '0006_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
